- README.md
> add Steve King

- README.md
Adding myself, which almost feels grimey but hey - why not!?
> added @fideloper

- README.md
Add PinguimDoLaravel and TioJobs
> Add PinguimDoLaravel and TioJobs

- README.md
> Programming With Geo. 

- README.md
> Adding 28 YouTube channels 

- README.md
Added an english speaking youtuber and several french speaking ones.
> ✨ feat: added GaryClarkeTech, YoanDev, Grafikart, Toham, LiorChamla

- README.md
Caleb Porzio is every week doing the bunch of cool stuff. 😎
> Add Livewire

- README.md
Two channels enricher of knowledge.
> Add: Webmentor, Club Full-Stack

- README.md
**DifferDev by Leonardo Tumadjian**
> feat: add differdev youtube channel

- README.md
> feat: add celke youtube channel

- README.md
He made good amount of YouTube videos for laravel community on Livewire, filamentPHP etc
> Adding Amitav Roy

- README.md
add 1 channel that talks about laravel and deploy
> Update add line de channel from youtube in README.md

- README.md
Filament daily is created by Povilas Korop
> adding filament daily

- README.md
> add rmsramos youtube channel

- update.php
This way the script can be re-run regularly and not break the list
> Added parsing 2 versions of lines: with and without followers.

- README.md
> Add @simonhamp

- README.md
Sorry.. I thought I actually PR'ed it when I forked it yesterday but apparently not 🤦🏻‍♂️ I promise I know how to Internet.
> Add Matt Stauffer

- README.md
found him from Laravel news, making nice videos
> added laravel school

- README.md
I've no association with the channel, I just enjoy the show.
> add PHPUgly

- README.md
Hey there! I've been diving deep into PHP and sharing my learnings on my YouTube channel. If you're into expanding your YouTubers list, I'd appreciate you checking out my content. Thanks for the support, and happy coding!
> Jacked PHP Suggestion

- README.md
> Add BR developpers

- README.md
Fixed the link @hrsa.
Not sure if I needed to order it, though - or if the script will do it's thing..?
> Adding Andrew Cairns

- README.md
> feat: add @phpislife channel

- README.md
> Add @icodestuff as a creator

- README.md
- Channel - https://www.youtube.com/@Maniruzzaman
- Subscriber - 13.8K
- Video Topics - PHP, Laravel, React JS.
> Added @Maniruzzaman

- README.md
[https://www.youtube.com/@LaravelTurkiye](https://www.youtube.com/@LaravelTurkiye)
> Add @LaravelTurkiye

- README.md
> Update README.md - Added @lessonsim Channel

- README.md
> Add @nexxai_dev

- README.md
Thanks for putting this together! See this PR for adding Server Side Up to the list. 👍
> Add @serversideupnet

- README.md
**EspecializaTi by Carlos Ferreira**
> feat: add EspecializaTi youtube channel

- README.md
> feat: add "Josh Cirre" youtube channel
